server:
  port: 8099

spring:
  application:
    name: courier-tracking

  mvc:
    problemdetails:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:file:./data/courier-tracking;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html

courier-tracking:
  store:
    store-file-resource: classpath:db/data/stores.json
    radius-meters: 100
    reentry-cooldown: PT1M
  courier:
    min-movement-meters: 10
    max-speed-kmh: 150
